version: "3.9"

services:
  load_balancer:
    build: .
    image: flash_app
    container_name: load_balancer_container
    ports:
      - "6000:6000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      -  net1

networks:
  net1:
    driver: bridge
